const express = require('express');
const router = express.Router();
const user = require('./user');
const book = require('./book');
const profile = require('./profile');
const report = require('./report');
router.use('/user', user);
router.use('/book', book);
router.use('/profile', profile);
router.use('/report', report);
module.exports = router;